### ISSUE TITLE
[Beginner Question (again)] How do I read multiple data structures without reading the file multiple times?

### ISSUE THREAD

**Issue by YannZeRookie** [Cinchoo/ChoETL#125]
I have another beginner question: the examples of the (great) documentation always show cases in which there is always one single type of objects or structures to read. In real life, I have YAML files that contain several different structures, like a list of persons and a list of cities (see below). Each list would map to an array of different classes. How do I go about it without reading the file twice or without grabbing the whole file as a big object that would need to be re-converted afterwards?

Consider the following YAML file:
```
creation: 2020-12-26
author: YannZeRookie
people:
  - id: 1
    name: Tom
  - id: 2
    name: Mark
cities:
  - id: 1
    city: San Francisco
    state: CA
    country: USA
  - id: 2
    city: Palo Alto
    state: CA
    country: USA
  - id: 3
    city: Minneapolis
    state: MN
    country: USA
```

Here I am reading it twice, which seems wrong to me:
```
    public class PeopleInfo
    {
        public string id { get; set; }
        public string name { get; set; }
    }

    public class CityInfo
    {
        public string id { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
    }

void TestTwoLists()
        {
            string yaml = @"
creation: 2020-12-26
author: YannZeRookie
people:
  - id: 1
    name: Tom
  - id: 2
    name: Mark
cities:
  - id: 1
    city: San Francisco
    state: CA
    country: USA
  - id: 2
    city: Palo Alto
    state: CA
    country: USA
  - id: 3
    city: Minneapolis
    state: MN
    country: USA
";
            using (var r = ChoYamlReader<PeopleInfo>.LoadText(yaml)
                .WithYamlPath("$.people[*]")
            )
            {
                foreach (var rec in r)
                    Console.WriteLine(rec.Dump());
            }

            using (var r = ChoYamlReader<CityInfo>.LoadText(yaml)
                .WithYamlPath("$.cities[*]")
            )
            {
                foreach (var rec in r)
                    Console.WriteLine(rec.Dump());
            }
        }

```
